# docker-compose.yml

version: '3.8'

services:
  # Service 1: Ollama (The LLM)
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434" # Expose Ollama port to the host
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu] # This gives the container access to the GPU
    restart: unless-stopped

  # Service 2: Your Node.js Backend
  backend:
    build:
      context: ./backend # Tells Docker to use the Dockerfile in ./backend
    env_file:
      - ./backend/.env # Loads your .env file
    ports:
      - "5000:5000" # Expose port 5000
    depends_on:
      - ollama # Won't start until Ollama is ready
    restart: unless-stopped

  # Service 3: Nginx (Frontend & Proxy)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80" # This is the main port for your website
    volumes:
      # Mounts your *built* React app into the Nginx server
      - ./frontend/build:/usr/share/nginx/html
      # Mounts your Nginx config file
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend # Won't start until the backend is ready
    restart: unless-stopped

volumes:
  ollama_data: # This persists your downloaded Ollama models