version: '3.8'

services:
  # Backend Service Configuration
  backend:
    build: ./backend
    container_name: aiprep_backend
    # You can define environment variables here or link to your .env file
    environment:
      - PORT=5000
      # e.g., DATABASE_URL=...
    # The backend doesn't need its port exposed to the world,
    # as Nginx will handle the communication.

  # Frontend Service Configuration
  frontend:
    build: ./frontend
    container_name: aiprep_frontend
    ports:
      # Map your local machine's port 80 to the container's port 80
      - "80:80"
    volumes:
      # Mount our Nginx config file into the container
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    # Make sure the backend is started before the frontend
    depends_on:
      - backend